### ISSUE TITLE
[Bug] [Linux] GoldSrc games not opening on Fedora 41 with Flatpak Steam

### ISSUE THREAD

**Issue by CombineSoldier14** [shdwmtr/millennium#169] opened 2024-11-15 22:51 UTC
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a theme
- [X] My issue is not caused by a plugin

### Describe the Bug

When opening any GoldSrc game (half-life 1, cs 1.6, etc) on their linux ports, it immediatly crashes with nothing opening. I get this error in the console:

```
Adding process 15053 for gameID 70
STEAM /bin/bash: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/libtinfo.so.6: no version information available (required by /bin/bash)
STEAM pid 15170 != 15166, skipping destruction (fork without exec?)
STEAM pid 15175 != 15166, skipping destruction (fork without exec?)
STEAM /bin/bash: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/libtinfo.so.6: no version information available (required by /bin/bash)
STEAM /bin/bash: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/libtinfo.so.6: no version information available (required by /bin/bash)
STEAM pid 15196 != 15166, skipping destruction (fork without exec?)
STEAM Adding process 15166 for gameID 70
STEAM /home/combinesoldier14/.local/share/Steam/steamapps/common/Half-Life/hl_linux: error while loading shared libraries: libpython-3.11.8.so: cannot open shared object file: No such file or directory
STEAM Adding process 15197 for gameID 70
STEAM Game Recording - game stopped [gameid=70]
```

When launching Steam without millennium, the games run fine. I tried to find this Python library but it seems to not exist anymore on the Fedora repos.

### Expected Behavior

Games open and run fine as normal without millennium

### Steps To Reproduce

1. Use Fedora 41 KDE
2. Install Steam flatpak
3. Install Millennium [with the shell script](https://docs.steambrew.app/users/installing/)
4. Run Millennium via the start.sh script
5. Install and try to run any GoldSrc game

### Operating System

Linux

**Comment by Chorwacjen** [comment] 2024-11-16 13:32
it seems close to what happened to me in #119 because libpython is also giving out an error here

**Comment by shdwmtr** [comment] 2024-11-16 16:15
It might have something to do with the flatpak version of Steam. Millennium wasn't developed to be used in flatpak Steam

**Comment by CombineSoldier14** [comment] 2024-11-17 00:08
I'll try non flatpak steam

**Comment by CombineSoldier14** [comment] 2024-11-17 00:17
Tried it, still same error.
```
STEAM Adding process 5596 for gameID 70
STEAM pid 5600 != 5596, skipping destruction (fork without exec?)
STEAM pid 5605 != 5596, skipping destruction (fork without exec?)
STEAM /bin/bash: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/libtinfo.so.6: no version information available (required by /bin/bash)
STEAM /bin/bash: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/libtinfo.so.6: no version information available (required by /bin/bash)
STEAM pid 5626 != 5596, skipping destruction (fork without exec?)
STEAM /home/combinesoldier14/.local/share/Steam/steamapps/common/Half-Life/hl_linux: error while loading shared libraries: libpython-3.11.8.so: cannot open shared object file: No such file or directory
STEAM Adding process 5627 for gameID 70
```

**Comment by shdwmtr** [comment] 2024-11-17 17:07
@CombineSoldier14 Are you also on Fedora? On arch I can't seem to reproduce the issue.

**Comment by CombineSoldier14** [comment] 2024-11-17 17:30
Yeah, this is all on Fedora 41.

**Comment by shdwmtr** [comment] 2024-11-17 20:42
run `ldd ~/.local/share/Steam/steamapps/common/Half-Life/hl_linux` and share its output

**Comment by CombineSoldier14** [comment] 2024-11-19 01:43
Thanks! That works.

**Comment by shdwmtr** [comment] 2024-11-27 05:15
Try this build: https://github.com/shdwmtr/millennium/actions/runs/12043783338

It should hopefully fix those issues

**Comment by Chorwacjen** [comment] 2024-11-30 13:58
Oh I forgot to reply although I thought I did...
Okay, well, the build you provided DOES work but the logs from the terminal are such a mess that I prefer running Steam first and then Millenium. However, these are only visual nuances, because I believe everything works fine (I could launch games without issue, but the logs looked unappealing visually for me). I think it fixes this issue pretty much.

**Comment by shdwmtr** [comment] 2024-12-29 04:48
This should be fixed as of the latest version!

**Closed by shdwmtr** 2024-12-29 04:48 UTC
Labels: bug
